language: python
install: pip install tox
script: tox -v -e $TOX_ENV -- --verbose
sudo: false
env:
  - TOX_ENV=py27-django111
  # It is annoying that travis + tox doesn't support python 3.6
  # - TOX_ENV=py36-django111
  # - TOX_ENV=py36-django20
  - TOX_ENV=flake8
notifications:
  email:
    - jason.louard.ward@gmail.com
