language: python
dist: xenial
python:
  - "3.7"
install: pip install tox
script: tox -v -e $TOX_ENV -- --verbose
sudo: false
env:
  - TOX_ENV=py27-django111
  - TOX_ENV=py37-django111
  - TOX_ENV=py37-django22
  - TOX_ENV=flake8
notifications:
  email:
    - jason.ward@policystat.com
